steps:
  install:
    image: node:20-slim
    commands:
      - npm install
      # npm ci failed for some reason
  release:
    image: plugins/npm
    settings:
      token:
        from_secret: npm_access_token
when:
  - event: tag
    ref: refs/tags/v*
