pipeline:
  test:
    image: danlynn/ember-cli:3.24.0
    commands:
      - npm ci
      - npm run lint:js
      - npm run lint:hbs
      # - npm run test:ember
    # Pipeline level conditions aren't supported yet:
    # https://github.com/woodpecker-ci/woodpecker/issues/283
    when:
      event:
        - pull_request
